name: bShortcut
main: com.beecub.bShortcut.bShortcut
version: 1.1.0
author: beecub
description: >
             Shortcuts
commands:
  bShortcut:
    description: Reload Command for bShortcut
    usage: |
           /<command> [reload]